### ISSUE TITLE
Backend: Dev-CLI: serviceWorker.js not found

### ISSUE THREAD

**Issue by chr5tphr** [virelay/virelay#17]
When running the server using the dev-CLI `python -m virelay`, whenever a client connects, the backend attempts to unsuccessfully serve `virelay/frontend/distribution/serviceWorker.js`.

<details>
<summary>Traceback</summary>

```
2022-03-23 18:19:54,761] ERROR in app: Exception on /serviceWorker.js [GET]
Traceback (most recent call last):
  File ".venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File ".venv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File ".venv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File ".venv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "virelay/server.py", line 119, in <lambda>
    resource_stream('virelay', os.path.join(frontend_path, target).format(file_name)),
  File ".venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1136, in resource_stream
    return get_provider(package_or_requirement).get_resource_stream(
  File ".venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1608, in get_resource_stream
    return open(self._fn(self.module_path, resource_name), 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'virelay/frontend/distribution/serviceWorker.js'
```
</details>

**Comment by lecode-official** [comment]
I am not quite sure why `serviceWorker.js` should be loaded. Maybe Angular just tries to load it and has a fallback in case it is not available. I'll have to check that. But in general, it would be a good idea to wrap the loading of the file in a `try`-`except` block and return an HTTP 404 Not Found if the file does not exist.

**Comment by lecode-official** [comment]
Okay, I looked into the problem and I could not figure out why `serviceWorker.js` was loaded in the first place, because a service worker seems to be a local proxy which intercepts all requests that are made in order to cache them. This is only required in order to convert the Angular application into a progressive web app (PWA), i.e., a website that can be "installed" to look like a real app.

Maybe this is something that the Angular CLI injects into the development build to implement hot reloading? I have no clue!

Nonetheless, as I have stated above, it is still not very nice to get an HTTP 500 Internal Server error for what should be an HTTP 404 Not Found. So I have added a check that returns an HTTP 404 if the requested file does not exist.

If you can provide more information, then please reopen this issue.
